@startuml
title Схема обработки запроса

actor Client
participant Transport
participant Service
participant Repository
participant DB



Client -> Transport : Request
Transport -> Service : Method(ctx, args)

Service -> Repository : Method1(args)
Repository -> DB : Query
DB --> Repository : result
Repository --> Service : result

Service -> Repository : Method2(args)
Repository -> DB : Query
DB --> Repository : result
Repository --> Service : result

Service --> Transport : result, err
Transport --> Client : Response

@enduml