// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/basic_repository.go
//
// Generated by this command:
//
//	mockgen -source=pkg/basic_repository.go -destination=internal/service/mocks/mock_basic_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "main/pkg/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIBasicRepository is a mock of IBasicRepository interface.
type MockIBasicRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIBasicRepositoryMockRecorder
	isgomock struct{}
}

// MockIBasicRepositoryMockRecorder is the mock recorder for MockIBasicRepository.
type MockIBasicRepositoryMockRecorder struct {
	mock *MockIBasicRepository
}

// NewMockIBasicRepository creates a new mock instance.
func NewMockIBasicRepository(ctrl *gomock.Controller) *MockIBasicRepository {
	mock := &MockIBasicRepository{ctrl: ctrl}
	mock.recorder = &MockIBasicRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBasicRepository) EXPECT() *MockIBasicRepositoryMockRecorder {
	return m.recorder
}

// AddHistoryPg mocks base method.
func (m *MockIBasicRepository) AddHistoryPg(Record models.History) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddHistoryPg", Record)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddHistoryPg indicates an expected call of AddHistoryPg.
func (mr *MockIBasicRepositoryMockRecorder) AddHistoryPg(Record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHistoryPg", reflect.TypeOf((*MockIBasicRepository)(nil).AddHistoryPg), Record)
}

// AddModel mocks base method.
func (m *MockIBasicRepository) AddModel(table string, Record any) (int, models.History, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddModel", table, Record)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(models.History)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddModel indicates an expected call of AddModel.
func (mr *MockIBasicRepositoryMockRecorder) AddModel(table, Record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddModel", reflect.TypeOf((*MockIBasicRepository)(nil).AddModel), table, Record)
}

// UpdatePg mocks base method.
func (m *MockIBasicRepository) UpdatePg(table string, recordId int, Record any) (int, models.History, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePg", table, recordId, Record)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(models.History)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdatePg indicates an expected call of UpdatePg.
func (mr *MockIBasicRepositoryMockRecorder) UpdatePg(table, recordId, Record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePg", reflect.TypeOf((*MockIBasicRepository)(nil).UpdatePg), table, recordId, Record)
}
