// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/device.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/device.go -destination=internal/service/mocks/mock_device_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	repository "main/internal/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIDeviceRepository is a mock of IDeviceRepository interface.
type MockIDeviceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIDeviceRepositoryMockRecorder
	isgomock struct{}
}

// MockIDeviceRepositoryMockRecorder is the mock recorder for MockIDeviceRepository.
type MockIDeviceRepositoryMockRecorder struct {
	mock *MockIDeviceRepository
}

// NewMockIDeviceRepository creates a new mock instance.
func NewMockIDeviceRepository(ctrl *gomock.Controller) *MockIDeviceRepository {
	mock := &MockIDeviceRepository{ctrl: ctrl}
	mock.recorder = &MockIDeviceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeviceRepository) EXPECT() *MockIDeviceRepositoryMockRecorder {
	return m.recorder
}

// GetActiveNode mocks base method.
func (m *MockIDeviceRepository) GetActiveNode(ctx context.Context, device string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveNode", ctx, device)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveNode indicates an expected call of GetActiveNode.
func (mr *MockIDeviceRepositoryMockRecorder) GetActiveNode(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveNode", reflect.TypeOf((*MockIDeviceRepository)(nil).GetActiveNode), ctx, device)
}

// GetDeviceRelations mocks base method.
func (m *MockIDeviceRepository) GetDeviceRelations(ctx context.Context, device string) ([]repository.DeviceRelations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceRelations", ctx, device)
	ret0, _ := ret[0].([]repository.DeviceRelations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceRelations indicates an expected call of GetDeviceRelations.
func (mr *MockIDeviceRepositoryMockRecorder) GetDeviceRelations(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceRelations", reflect.TypeOf((*MockIDeviceRepository)(nil).GetDeviceRelations), ctx, device)
}

// UpdateConnection mocks base method.
func (m *MockIDeviceRepository) UpdateConnection(ctx context.Context, device, datetime string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConnection", ctx, device, datetime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConnection indicates an expected call of UpdateConnection.
func (mr *MockIDeviceRepositoryMockRecorder) UpdateConnection(ctx, device, datetime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConnection", reflect.TypeOf((*MockIDeviceRepository)(nil).UpdateConnection), ctx, device, datetime)
}
