// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/event.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/event.go -destination=internal/service/mocks/mock_event_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIEventRepository is a mock of IEventRepository interface.
type MockIEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIEventRepositoryMockRecorder
	isgomock struct{}
}

// MockIEventRepositoryMockRecorder is the mock recorder for MockIEventRepository.
type MockIEventRepositoryMockRecorder struct {
	mock *MockIEventRepository
}

// NewMockIEventRepository creates a new mock instance.
func NewMockIEventRepository(ctrl *gomock.Controller) *MockIEventRepository {
	mock := &MockIEventRepository{ctrl: ctrl}
	mock.recorder = &MockIEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEventRepository) EXPECT() *MockIEventRepositoryMockRecorder {
	return m.recorder
}

// CheckDouble mocks base method.
func (m *MockIEventRepository) CheckDouble(ctx context.Context, checkDate, equipmentModel string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDouble", ctx, checkDate, equipmentModel)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckDouble indicates an expected call of CheckDouble.
func (mr *MockIEventRepositoryMockRecorder) CheckDouble(ctx, checkDate, equipmentModel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDouble", reflect.TypeOf((*MockIEventRepository)(nil).CheckDouble), ctx, checkDate, equipmentModel)
}

// SaveErrEvent mocks base method.
func (m *MockIEventRepository) SaveErrEvent(ctx context.Context, errEvent []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveErrEvent", ctx, errEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveErrEvent indicates an expected call of SaveErrEvent.
func (mr *MockIEventRepositoryMockRecorder) SaveErrEvent(ctx, errEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveErrEvent", reflect.TypeOf((*MockIEventRepository)(nil).SaveErrEvent), ctx, errEvent)
}
