// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/user.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/user.go -destination=internal/service/mocks/mock_user_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "main/internal/models"
	repository "main/internal/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIUserRepository is a mock of IUserRepository interface.
type MockIUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUserRepositoryMockRecorder
	isgomock struct{}
}

// MockIUserRepositoryMockRecorder is the mock recorder for MockIUserRepository.
type MockIUserRepositoryMockRecorder struct {
	mock *MockIUserRepository
}

// NewMockIUserRepository creates a new mock instance.
func NewMockIUserRepository(ctrl *gomock.Controller) *MockIUserRepository {
	mock := &MockIUserRepository{ctrl: ctrl}
	mock.recorder = &MockIUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserRepository) EXPECT() *MockIUserRepositoryMockRecorder {
	return m.recorder
}

// CreateCache mocks base method.
func (m *MockIUserRepository) CreateCache(ctx context.Context, device string, users []models.UserCard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCache", ctx, device, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCache indicates an expected call of CreateCache.
func (mr *MockIUserRepositoryMockRecorder) CreateCache(ctx, device, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCache", reflect.TypeOf((*MockIUserRepository)(nil).CreateCache), ctx, device, users)
}

// DropCache mocks base method.
func (m *MockIUserRepository) DropCache(ctx context.Context, device string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropCache", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropCache indicates an expected call of DropCache.
func (mr *MockIUserRepositoryMockRecorder) DropCache(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropCache", reflect.TypeOf((*MockIUserRepository)(nil).DropCache), ctx, device)
}

// GetByGid mocks base method.
func (m *MockIUserRepository) GetByGid(ctx context.Context, gID string) (int, models.UserCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGid", ctx, gID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(models.UserCard)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByGid indicates an expected call of GetByGid.
func (mr *MockIUserRepositoryMockRecorder) GetByGid(ctx, gID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGid", reflect.TypeOf((*MockIUserRepository)(nil).GetByGid), ctx, gID)
}

// GetUserCache mocks base method.
func (m *MockIUserRepository) GetUserCache(ctx context.Context, device, index string) (*models.UserCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCache", ctx, device, index)
	ret0, _ := ret[0].(*models.UserCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCache indicates an expected call of GetUserCache.
func (mr *MockIUserRepositoryMockRecorder) GetUserCache(ctx, device, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCache", reflect.TypeOf((*MockIUserRepository)(nil).GetUserCache), ctx, device, index)
}

// GetUserRelations mocks base method.
func (m *MockIUserRepository) GetUserRelations(ctx context.Context, userGid string) (repository.UserRelations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRelations", ctx, userGid)
	ret0, _ := ret[0].(repository.UserRelations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRelations indicates an expected call of GetUserRelations.
func (mr *MockIUserRepositoryMockRecorder) GetUserRelations(ctx, userGid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRelations", reflect.TypeOf((*MockIUserRepository)(nil).GetUserRelations), ctx, userGid)
}

// GetUsersByNodes mocks base method.
func (m *MockIUserRepository) GetUsersByNodes(ctx context.Context, nodeIds []string) ([]models.UserCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByNodes", ctx, nodeIds)
	ret0, _ := ret[0].([]models.UserCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByNodes indicates an expected call of GetUsersByNodes.
func (mr *MockIUserRepositoryMockRecorder) GetUsersByNodes(ctx, nodeIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByNodes", reflect.TypeOf((*MockIUserRepository)(nil).GetUsersByNodes), ctx, nodeIds)
}

// GetWorkerId mocks base method.
func (m *MockIUserRepository) GetWorkerId(ctx context.Context, cardId, projectId int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerId", ctx, cardId, projectId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkerId indicates an expected call of GetWorkerId.
func (mr *MockIUserRepositoryMockRecorder) GetWorkerId(ctx, cardId, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerId", reflect.TypeOf((*MockIUserRepository)(nil).GetWorkerId), ctx, cardId, projectId)
}
