// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/user.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/user.go -destination=internal/service/mocks/mock_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	rep "main/internal/repository"
	"main/pkg"

	gomock "go.uber.org/mock/gomock"
)

type RepositoryInterface struct {
	Common pkg.IBasicRepository
	User   rep.IUserRepository
	Device rep.IDeviceRepository
	Event  rep.IEventRepository
}

func NewMockRepo(ctrl *gomock.Controller) RepositoryInterface {
	return RepositoryInterface{
		Common: NewMockIBasicRepository(ctrl),
		User:   NewMockIUserRepository(ctrl),
		Device: NewMockIDeviceRepository(ctrl),
		Event:  NewMockIEventRepository(ctrl),
	}
}
